### ISSUE TITLE
Right way to handle mouse event

### ISSUE THREAD

**Issue by rgiot** [Gekkio/imgui-rs#104]
What is the best way to handle mouse events within our interface generation code ?
I wanted to interact on buttons when they are hovered and when the mouse is pressed and I have been unable to find a proper way to do that.

The dirty way consists in modifying the support library provided with the examples in order to provide the mouse state to the application:

```diff
diff --git a/rust/src/support/mod.rs b/rust/src/support/mod.rs
index 85a9d6c..74321a7 100644
--- a/rust/src/support/mod.rs
+++ b/rust/src/support/mod.rs
@@ -3,13 +3,13 @@ use imgui_gfx_renderer::{Renderer, Shaders};
 use std::time::Instant;

 #[derive(Copy, Clone, PartialEq, Debug, Default)]
-struct MouseState {
-    pos: (i32, i32),
-    pressed: (bool, bool, bool),
-    wheel: f32,
+pub struct MouseState {
+ pub   pos: (i32, i32),
+ pub   pressed: (bool, bool, bool),
+ pub   wheel: f32,
 }

-pub fn run<F: FnMut(&Ui) -> bool>(title: String, clear_color: [f32; 4], mut run_ui: F) {
+pub fn run<F: FnMut(&Ui, &MouseState) -> bool>(title: String, clear_color: [f32; 4], mut run_ui: F) {
     use gfx::{self, Device};
     use gfx_window_glutin;
     use glutin::{self, GlContext};
@@ -135,7 +135,7 @@ pub fn run<F: FnMut(&Ui) -> bool>(title: String, clear_color: [f32; 4], mut run_
         let size_pixels = window.get_inner_size_pixels().unwrap();

         let ui = imgui.frame(size_points, size_pixels, delta_s);
-        if !run_ui(&ui) {
+        if !run_ui(&ui, &mouse_state) { 
             break;
         }

```

and in the code of the interface to use stuff in the sys namespace (is_item_hovered does not work when mouse is pressed) :

```rust
 if sys::igIsItemHovered(sys::ImGuiHoveredFlags::AllowWhenBlockedByPopup | sys::ImGuiHoveredFlags::AllowWhenBlockedByActiveItem) && mouse.pressed.0 {
 ...
}
```

But I guess it is not the good way to do that ...

**Comment by NPN** [comment]
Until the library wraps mouse events, there isn't really a best way to handle them. However, one way to handle them without modifying the support library is to call unsafe functions such as `imgui_sys::igIsMouseDown` or `imgui_sys::igIsMouseClicked`.

**Comment by rgiot** [comment]
Thanks, I had not seen these methods... I have been able to restore support library to its initial state
