### ISSUE TITLE
Provide way to get keyboard input

### ISSUE THREAD

**Issue by mruegenberg** [Gekkio/imgui-rs#105]
Hello,
apparently there is no imgui-rs way to capture keyboard input. In the original imgui, there are functions like `IsKeyDown`, `IsKeyPressed` etc.
It would be nice to get something similar.

The easiest way would probably be to just expose an accessor function for `io.keys_down` in combination with `io.key_map`, to be used in the same way as we can do `ui.imgui().mouse_pos();` already.
(I've tried to use this manually, but the io() method is private.)

Use case: capturing the escape button to close my program while testing.

**Comment by malikolivier** [comment]
I just realized the same issue and thought about to make a PR to provide this kind of features.

The unsafe function `igIsKeyPressed` is present and can be used as is in the `imgui-sys` crates.

**Comment by mruegenberg** [comment]
Cool, that definitely helped. (Of course, a safe/more Rust-like version would still be helpful.)
