### ISSUE TITLE
API question: why provide `delta_time` manually? 

### ISSUE THREAD

**Issue by matklad** [Gekkio/imgui-rs#11]
This is more of a question then of a feature request. I wonder why does the [frame](https://github.com/Gekkio/imgui-rs/blob/master/src/lib.rs#L227) function takes `delta_time` as an argument? This is quite error-prone (you can easily pass a negative amount of time, or milliseconds instead of seconds) and requires manual management of a bit of state. 

Why can't `ImGui` just store a `SteadyTime` as a field and update it on every `frame` call?

**Comment by Gekkio** [comment]
There's a couple of reasons:

* it matches with the underlying API. The raw ImGui API tries to be flexible and not make too many design decisions that it doesn't need to care about. The goal of imgui-rs is to provide a high-level but still lightweight wrapper on top of ImGui, so I don't want to add too much bookkeeping. This is also why the Glium renderer is just an optional extra thing.
* delta time is typically calculated anyway by the code that is calling imgui-rs
* I'd like to make the ImGui struct completely empty. There's currently log_filename and ini_filename, but I'm planning to remove these. ImGui should be an empty struct that is only used with the type system to prove lifetimes.

**Comment by matklad** [comment]
Thanks, it does make sense!
