### ISSUE TITLE
srgba support for gfx renderer?

### ISSUE THREAD

**Issue by robo-corg** [Gekkio/imgui-rs#129]
It looks like the renderer only accepts colors of gfx::format::Rgba8 which makes it messy to integrate with an app running using other color types.

I imagine it might not be possible to support arbitrary colors but an sRgba8 mode could be handy. I am not sure what sort of gfx magic you would need to do otherwise...

I hacked up the renderer to use srgba instead but I didn't really check to see if the colors looked right.

**Comment by Gekkio** [comment]
Yeah, it would be nice to support other color types as well...the last time I checked, the macros from gfx don't allow parameterizing over the color type, and using Srgba8 didn't fix the colours. Maybe things will be different after the gfx rewrite...?

**Comment by SpaceManiac** [comment]
I can say for sure that this is a `gfx` problem. At the very least the gfx opengl backend permanently sets `glEnable(GL_FRAMEBUFFER_SRGB)` which is not really what you want (you want to enable or disable this flag on a per-renderpass basis, and in particular you want it OFF for imgui; glium supports toggling this flag per-`Program`).

My workaround is thus:
```rs
device.with_gl(|gl| {
    gl.Disable(::gl::FRAMEBUFFER_SRGB);
});
```

**Comment by robo-hamburger** [comment]
Given both piston and ggez use srgb it would be quite nice to have this. I have to admit I really don't know that much about srgb. I know it is a color space and possibly a higher bpp color representation?

If it is just a color space thing I think I could live with the colors being wrong in my imgui given I probably won't use it in production.

Alternatively, I wonder if people would be interested in a ggez backend? It seems unnecessary given it just uses gfx-rs but it also seems like it might not be that much work.

**Comment by cosmicchipsocket** [comment]
Ran into this issue today as I am unable to pass an Srgb8 render target to imgui_gfx_renderer::Renderer(). I'm currently using Srgb8 as the color format in gfx because it otherwise makes the gamma way too bright.

**Comment by cosmicchipsocket** [comment]
I should note that I am using SDL2 to create the OpenGL context.

**Comment by cosmicchipsocket** [comment]
> Yeah, it would be nice to support other color types as well...the last time I checked, the macros from gfx don't allow parameterizing over the color type, and using Srgba8 didn't fix the colours. Maybe things will be different after the gfx rewrite...?

Using Srgba8 fixes this based on my own experience, and gfx does infact parameterize over color format, so imgui_gfx_renderer should too.

**Comment by Gekkio** [comment]
This is now implemented in the upcoming 0.1 release. `imgui-gfx-renderer` no longer uses the macro, and I've generated the code by hand and parameterized it with blend format, so it's possible to target both `Srgba8` and `Rgba8`. I don't know if the colours are actually correct in practice, but at least it compiles ;) 

No ETA for the 0.1 release yet though, so I'll keep this issue open for now.

**Comment by cosmicchipsocket** [comment]
Thanks for the update! I ended up simply forcing Rgb8 in my application (as Srgb was causing other issues as well).

**Comment by Gekkio** [comment]
Closing since `0.1.0-rc.1` brings Srgba8 support
