### ISSUE TITLE
[Regression] Custom drawing may be drawn outside the window

### ISSUE THREAD

**Issue by malikolivier** [Gekkio/imgui-rs#146]
I run the `test_window_impl` example and open the `custom_drawing` window.

Expected result (made from commit 1663e66):
![expected](https://user-images.githubusercontent.com/14120117/44019022-98bff718-9f18-11e8-8926-8c8145dacf41.png)

Real result (on master):
![result](https://user-images.githubusercontent.com/14120117/44019050-a098962a-9f18-11e8-95b7-4875af09e415.png)

As you can see, custom drawings are not cropped anymore. After bisecting, I found that the bug appeared in this commit: aa4ae70054208eea62b51f0e23420931331e89be.

@Gekkio At first glance, I don't know what caused the issue in your commit. My first guess is that there is an issue somewhere in how `fb_size` is used when setting `self.bundle.data.scissor`.

**Comment by Gekkio** [comment]
Good catch! I looked at the test window example briefly after my changes but didn't notice this problem before.

It's a simple thought error with the clip rect clamping...I'll fix it today and do another release

**Comment by Gekkio** [comment]
Fixed in 6a4286de1140394db98af38491702825da4c6155
