### ISSUE TITLE
Crash on minimize

### ISSUE THREAD

**Issue by Awpteamoose** [Gekkio/imgui-rs#148]
I'm using imgui-rs 0.0.20 with glium backend and the support function from current commit ([this](https://github.com/Gekkio/imgui-rs/blob/c22035250a3824e5297b450b93a836788961c2e5/imgui-examples/examples/support/mod.rs)).

I try with this:
```rust
support::run(String::from("test"), [1., 1., 1., 1.], |ui| {
	true
})
```

I get this error:
```
Assertion failed: (g.FrameCount == 0 || g.FrameCountEnded == g.FrameCount) && "Forgot to call Render() or EndFrame() at the end of the previous frame?", file third-party/cimgui/imgui/imgui.cpp, line 2272
```
as soon as I minimise.

I'm running Windows 10, rust nightly-2018-08-14-x86_64-pc-windows-msvc

**Comment by Awpteamoose** [comment]
Same thing happens with imgui-rs from repo.

**Comment by Gekkio** [comment]
Thanks for reporting this! 1eab502d012cd316e6f1c95281068b63dc33636f should fix the problem

**Comment by Awpteamoose** [comment]
Cheers, that does it.
