### ISSUE TITLE
Custom texture examples

### ISSUE THREAD

**Issue by adamsky** [Gekkio/imgui-rs#165]
From what I understand including examples for using custom textures was discussed in the related pull request. I thought I'd open an issue to keep the topic afloat. As a noob I would really enjoy some examples 🌱 

I don't really understand everything going on under the hood here yet. I was able to display a preloaded custom texture inside a window, but I'm struggling to think of a way of updating a texture at runtime.

**Comment by malikolivier** [comment]
For the time being, you will need to make your adapt the example support module to your own needs.

If you take a look at the current module, you will see that the `run_ui` function passes the `Ui` objects to your application with `run_ui(&ui)`.

https://github.com/Gekkio/imgui-rs/blob/77c79f4e612a8183f8ed6bd78fc68fbc0afaee71/imgui-glium-examples/examples/support/mod.rs#L83


If you use glium as a back-end, a solution is to pass the OpenGL `Context` and the `Textures` object along with Ui.

You can then create new textures in the main loop of your application with the OpenGL `Context` and register them to the `Textures` object, which belongs to the Renderer.

Something like this:
```rust
use std::rc::Rc;
use glium::{backend::Context, Texture2d};
use imgui::{Textures, Ui};
use imgui_glium_renderer::Renderer;

pub fn run<F>(config: AppConfig, mut run_ui: F) -> Result<()>
where
    F: FnMut(&Ui, &Rc<Context>, &mut Textures<Texture2d>) -> bool,
{
    // ... Initialize context

    loop {
        // ... UI Loop ...
        if !run_ui(&ui, display.get_context(), renderer.textures()) {
            break;
        }
    }
```

This is only a quick draft. I will be working on making a full example for at least one back-end.

**Comment by malikolivier** [comment]
For reference, I made a PR containing an example for custom textures https://github.com/Gekkio/imgui-rs/pull/180

I hope it helps.
