### ISSUE TITLE
macOS Mojave (10.14.1) blank screen, no errors.

### ISSUE THREAD

**Issue by shousper** [Gekkio/imgui-rs#172]
Hi,

Just updated my mac, found my project rendering a blank screen 😞. So I ran the examples for `imgui-rs` and `gfx-rs` to confirm if one of those were broken, and it looks like it's just `imgui-rs`.

I tired both `master` branch and `v0.0.21` code, all examples, even with the `glium` renderer gives me a blank window. Also tried switching off dark mode, just in case 😛, no luck though, haha.

Sorry I can't offer much more than that right. Let me know if I can do anything more to help!

Cheers.

**Comment by shousper** [comment]
Checked just now, the [imgui examples](https://github.com/ocornut/imgui/tree/master/examples) using metal or opengl2 work as well 👌. Trying to dig through `cimgui` and the `imgui-rs` bindings, but a little out of my depth!

**Comment by malikolivier** [comment]
I see a fix on the [CHANGELOG](https://github.com/tomaka/winit/blob/master/CHANGELOG.md) of version 0.18.0 of winit saying `Fix issue whereby the OpenGL context would not appear at startup on macOS Mojave (#1069)`.

You will need to update `glutin` to 0.19.0.
This is impossible to upgrade `glutin` if you use `glium` as a backend as latest `glium` still depends on an old version of `glutin`.

I made a PR to update `glutin` for the `gfx` back-end. Could you confirm that it fixes your issue? Thanks.
