### ISSUE TITLE
Is 0.1 branch usable?

### ISSUE THREAD

**Issue by rasky** [Gekkio/imgui-rs#177]
I need to start a largish project with imgui-rs. I read around and understood that 0.1 will break the API, and there is a pending PR. Should I start with that right away? Is it stable? Or it's better to start off master, even though I'll eventually be forced to update my code (will the migration be hard)?

(I'm opening a separate issue so that we can close it later without polluting the main "road to 0.1" issue)

**Comment by Gekkio** [comment]
It's not in usable state right now, so you should still use master for the time being. I don't know yet how tough migration will be, but it also depends on what features you use. If you do pretty simple stuff, it shouldn't be very difficult to migrate to 0.1 once the time comes.
