### ISSUE TITLE
ImDrawIdx too small

### ISSUE THREAD

**Issue by rickyhan** [Gekkio/imgui-rs#178]
I need to draw lots of elements via drawlist API. I'm wondering if there's a way to redefine the typedef of ImDrawIdx without recompiling imgui.

**Comment by Gekkio** [comment]
This isn't supported at the moment, so you'll need to fork imgui-rs and recompile both cimgui and imgui with some changes. In 0.1 I'll try to see if I can make a feature flag that can switch ImDrawIdx to a 32-bit value.

**Comment by sonoro1234** [comment]
With cimgui generator2 I thing that the only change needed before generation and compiling is to define ImDrawIdx in imconfig.h
