### ISSUE TITLE
Example showcasing displaying a jpeg image?

### ISSUE THREAD

**Issue by rickyhan** [Gekkio/imgui-rs#179]
Hi awesome library. Just wondering if there's an example code that displays any image using this library.

From what I've gathered so far. You insert your image into ui.textures (how?) and then use ui.image().build() to display it?

Thanks,
Ricky

**Comment by malikolivier** [comment]
Hi! I made a PR containing an example show-casing how to show an image.

https://github.com/Gekkio/imgui-rs/pull/180

Let us know if you have any question.
