### ISSUE TITLE
Examples should show how to take into account high-dpi screen resolutions

### ISSUE THREAD

**Issue by bjz** [Gekkio/imgui-rs#18]
Glutin allows you to query the high-dpi factor by calling `window.hidpi_factor()`. It would be good if the examples showed how to scale imgui by that factor so that it is not so tiny!

<img width="1136" alt="screen shot 2016-03-16 at 9 22 57 pm" src="https://cloud.githubusercontent.com/assets/695077/13809047/053623f2-ebbd-11e5-8308-71261630a8d8.png">

**Comment by Gekkio** [comment]
I recently got a new Dell laptop with a high-dpi screen, but I've found out that high-dpi is a mess on both Linux and Windows, so I can't use this laptop for testing. SDL2, GLFW3, and Glutin basically don't seem to have proper support for reading the frame buffer scale on X11, Wayland or Win32.

Could you confirm that the opengl3_example in the upstream ocornut/imgui repository scales as expected on OS X? If it works, I can apply the same ideas here.

**Comment by bjz** [comment]
Did you try `Window::hidpi_factor` with glutin?

I have it working on OS X, but I had implemented my own renderer. Kind of forgotten what I did. I couldn't figure out how to scale it up using nearest-neighbor though, so it looks blurry:

<img width="1112" alt="screen shot 2016-03-19 at 4 26 25 pm" src="https://cloud.githubusercontent.com/assets/695077/14761539/97db85fa-09a7-11e6-9cc4-ade657cdc5c3.png">

**Comment by Gekkio** [comment]
Yes, I tried `hidpi_factor` and verified from glutin sources that it's hard-coded to 1.0 on X11, Wayland and Win32. It probably works on OS X but I want to first confirm that imgui itself works with high dpi properly.

**Comment by bjz** [comment]
Related PR: ocornut/imgui#287
