### ISSUE TITLE
Transition imgui_glutin_support to winit

### ISSUE THREAD

**Issue by Benjamin-L** [Gekkio/imgui-rs#188]
I wrote [a crate](https://git.chronicembetterment.org/benjamin/imgui-winit/) for the boilerplate involved in coupling imgui and winit a while ago, but I just realized that there's already imgui_glutin_support, which does almost exactly the same thing. In fact, as far as I can tell all of stuff from glutin used in imgui_glutin_support are actually just public re-exports of stuff from winit. Ideally, imgui_glutin_support would become imgui_winit_support and just work with winit directly.

**Comment by repi** [comment]
That would indeed be great to have integrated in. Do a PR?

**Comment by Gekkio** [comment]
This is a great idea :smile: Implemented in eb5aaf1c2a758df8f63ab93949860e586c3df2c1

**Comment by Benjamin-L** [comment]
This looks perfect!
