### ISSUE TITLE
Wrong name for igSetNextWindowSizeConstraints

### ISSUE THREAD

**Issue by rasky** [Gekkio/imgui-rs#190]
The function `igSetNextWindowSizeConstraints`:
https://github.com/cimgui/cimgui/blob/67f3b097a5090dd074be959fb9c794bd75096a1c/cimgui.cpp#L209

is incorrectly bound as `igSetNextWindowConstraints`, causing a linking error when used.

**Comment by Gekkio** [comment]
Thanks for reporting this! Fixed in 7d364f6e5d3e3ce9a747208c788c53fdb60e88e6

**Comment by rasky** [comment]
thanks!
