### ISSUE TITLE
render to texture and use it as image

### ISSUE THREAD

**Issue by bekraoui** [Gekkio/imgui-rs#192]
hello, i'm new to Rust & gfx-rs, i' want to render to a texture and use that texture as an image to imgui , after several hours :-) i have created a texture using factory.view_texture_as_render_target successufully but i don't know how to use it as texture in imgui; ( ps : i have done this once using c++ as https://gamedev.stackexchange.com/questions/140693/how-can-i-render-an-opengl-scene-into-an-imgui-window?rq=1 )

what i have done until now:
```
/*start of code*/

//let _depth = factory.create_depth_stencil_view_only(width as u16, height as u16).unwrap();

let levels = 1;
let kind = gfx::texture::Kind::D2(width as u16, height as u16, gfx::texture::AaMode::Single);
//providing the storage configuration and requesting the capabilities
let texture_buf = factory.create_texture::<gfx::format::R8_G8_B8_A8>(kind, levels,  gfx::memory::Bind::SHADER_RESOURCE |  gfx::memory::Bind::RENDER_TARGET,  gfx::memory::Usage::Data, None).unwrap();

// creating an RTV for level 0
let target_tex = factory.view_texture_as_render_target::<ColorFormat>(&texture_buf, 0, None).unwrap();      

// creating an SRV for the whole mipmap range
let resource_tex = factory.view_texture_as_shader_resource::<ColorFormat>(&texture_buf, (0, levels-1), gfx::format::Swizzle::new()).unwrap(); 

/*end of code*/
```
thank you.
more ressources: http://www.opengl-tutorial.org/intermediate-tutorials/tutorial-14-render-to-texture/

**Comment by rickyhan** [comment]
Example: https://github.com/Gekkio/imgui-rs/blob/master/imgui-glium-examples/examples/custom_textures.rs#L53

**Comment by Gekkio** [comment]
There's now an example in master that shows how to use gfx textures: https://github.com/Gekkio/imgui-rs/blob/d11cae74d67504cf977f273ec47069118a0d6238/imgui-gfx-examples/examples/custom_textures.rs
