### ISSUE TITLE
Closeable window

### ISSUE THREAD

**Issue by Wowo10** [Gekkio/imgui-rs#195]
Hello!
I just tried to make my window closeable. I mean to have visible that close button in top right corner and I could not make it. I tried for kinda long time to search for it on Docs.rs and only going to src made my mind to use "opened()" function. Don`t you guys think that the name is a lil confusing? :)

**Comment by JoshLambda** [comment]
Yes, this is super weird, but that's the original way `ocornut/imgui` is working.
This should probably be inside a FAQ or on Docs.rs
Some example code below:
```
let mut window_opened = true;
loop {
    [...]
    // The window close button only toggles the boolean, that's why a conditional is needed
    if window_opened {
        ui.window(im_str!("edit_object"))
            .opened(&mut window_opened)
            .build(|| {
                ui.text(im_str!("Do something!"));
            });
    }
    [...]
}
```
