### ISSUE TITLE
Publish new release?

### ISSUE THREAD

**Issue by repi** [Gekkio/imgui-rs#212]
Possible to publish a new release of 0.0.23 on crates.io? 

It has been 2 months since the last one and a bunch of PRs (including some of our own from Embark) merged in.

**Comment by Gekkio** [comment]
Sure! I'll get it done today :smiley: 
I've been busy working on imgui-rs 0.1 and some other projects, and haven't even noticed so much time has passed

**Comment by repi** [comment]
Great, thanks!

**Comment by Gekkio** [comment]
0.0.23 is here :tada: :smiley:
