### ISSUE TITLE
Visible lag while drugging a window

### ISSUE THREAD

**Issue by xrombik** [Gekkio/imgui-rs#240]
When dragging the window with the mouse, there is a noticeable delay in the position of the window relative to the mouse pointer.
My system is:
OS: Linux Mint 19.1
Desktop: XFCE, x64.
CPU: Intel E5450 3.78GHz,
video: Radeon R270.

**Comment by Gekkio** [comment]
Can you try to run some of the upstream Dear ImGui C++ examples (e.g. [example_sdl_opengl3](https://github.com/ocornut/imgui/tree/master/examples/example_sdl_opengl3))? On my machine there's some visible lag, but imgui-rs examples and Dear ImGui C++ examples look similar, so it doesn't look like an imgui-rs problem.

**Comment by xrombik** [comment]
Thank you for your reply. Now I see that this is not an `imgui-rs` problem.
