### ISSUE TITLE
Are we GUI yet?

### ISSUE THREAD

**Issue by nestordemeure** [Gekkio/imgui-rs#254]
I just noticed that imgui-rs is not mentionned on the [Are we GUI yet?](https://areweguiyet.com/#ecosystem) page which lists all packages that can be used to build a GUI in Rust.

Making a pull request to add it would increase the visibility of the project.

**Comment by Jezza** [comment]
I opened a [PR](https://github.com/areweguiyet/areweguiyet/pull/22).

Tags: "Immediate mode API" and "Bindings"
