### ISSUE TITLE
Issues with Text Input

### ISSUE THREAD

**Issue by sanboxrunner** [Gekkio/imgui-rs#268]
Hi, I'm doing a TextInput box like this:

```rs
    pub fn inspect(&mut self, ui: &Ui<'_>, label: &ImStr) -> bool {
        let mut name = ImString::new(&self.name);
        let ret = ui.input_text(label, &mut name).build();
        if ret {
            self.name = format!("{}", name);
        }
        ret
    }
```

```rs
pub struct Name {
    pub name: String,
}
```

Is this the right way to do such a thing? When I do this, if I backspace all the way to 0 characters, I no longer get a true back form `.build()` when I try to type further characters, which means I can't edit the string anymore.

Thanks!

**Comment by coolit** [comment]
This occurred to me too. The solution is, use ImString type instead of String.
