### ISSUE TITLE
How to lower frame rate to save cpu usage

### ISSUE THREAD

**Issue by coolit** [Gekkio/imgui-rs#274]
In my case, the test-window program used 10-40%+ out of 2.4GHz cpu on a win10 64bit laptop, depending on the visible GUI area. Same high usage under release mode. And the cpu usage might go as high as 90% in some program I wrote.
So I was wondering is there a way to lower the frame rate, so as to lower the CPU usage? 
Thanks.

**Comment by coolit** [comment]
problem solved

**Comment by XZCendence** [comment]
What did you do?
