### ISSUE TITLE
Customize sampling with glium

### ISSUE THREAD

**Issue by alexkirsz** [Gekkio/imgui-rs#287]
The glium renderer always samples with linear interpolation:

https://github.com/Gekkio/imgui-rs/blob/ccec55c10a787f92b21054476f5817506c38692e/imgui-glium-renderer/src/lib.rs#L198-L200

I have a use case where I'd like to set this to Nearest: displaying sprites at magnified scales, where the original pixels should be clearly visible. For now, I've simply replaced the filter in the source of the renderer, but it'd be nice to customize this on a per-texture basis.

**Comment by cosmicchipsocket** [comment]
Seconding this. I'm working on an editor where you specify a series of UV coordinates and this would be easier to do when zooming in to see the individual pixels. I don't want to fork the renderer just to change this.
