### ISSUE TITLE
ImString::refresh_size truncates the null delimiter

### ISSUE THREAD

**Issue by Taywee** [Gekkio/imgui-rs#289]
ImString::refresh_size ([currently located here](https://github.com/Gekkio/imgui-rs/blob/ccec55c10a787f92b21054476f5817506c38692e/src/string.rs#L95-L100)) currently looks like this:

```rust
    pub(crate) fn refresh_len(&mut self) {
        let len = self.to_str().len();
        unsafe {
            self.0.set_len(len);
        }
    }
```
ImStr::to_str returns a string slice without the null byte, so when this is executed, the length of the vector is set in a way that truncates the null byte.  This doesn't typically cause problems in practice, because the storage will still be reserved and will still have the null byte. If you clone the ImString, however, the vector is cloned, and a vector clone clones based on the slice, not the entire buffer, so you end up potentially reading garbage.

In my case, I found this by having a text field, creating a pop-up modal to edit the text field, keeping an edit buffer, and assigning a clone of the edit buffer to the previous text field value.  It spontaneously is corrupted.  A `dbg!` shows that it's the output of the `.clone()` operation itself that is corrupt.

**Comment by Gekkio** [comment]
Thanks for the report! I knew there was an off-by-one error somewhere, but never had the time to investigate this further.

**Comment by Gekkio** [comment]
Should be fixed by https://github.com/Gekkio/imgui-rs/commit/d82bc65934d795e1952598c38ebe439f1e35c31b
