### ISSUE TITLE
Release with winit 0.21/0.20

### ISSUE THREAD

**Issue by aentity** [Gekkio/imgui-rs#297]
Is it possible to get a release soon with winit 0.20/0.21; the current version uses alpha, which can be upgraded to 0.20 by cargo, which has a breaking change. I think only change required is some functions requiring LogicalPosition?

**Comment by Gekkio** [comment]
Yeah, I was waiting for a new winit 0.21-compatible Glium release, which finally happened yesterday :smile: 

I'll do the necessary upgrades and a new release later this week.

**Comment by aentity** [comment]
Awesome, thanks much! :)

**Comment by aclysma** [comment]
As far as I can tell, none of the breaking changes impacted imgui-winit-support. I PR'ed a cargo.toml change to allow building against 0.21 here: https://github.com/Gekkio/imgui-rs/pull/300

**Comment by Gekkio** [comment]
0.3.0 is now out :tada:
