### ISSUE TITLE
Unable to start new project (winit dependency problem)

### ISSUE THREAD

**Issue by akx** [Gekkio/imgui-rs#304]
Hey there!

I'm bumping into a problem where I can't start a new project using `imgui-rs` due to two mutually incompatible copies of the `winit` crate.

My `cargo.toml` dependencies, based on the examples, look like

```
[dependencies]
imgui = "0.3.0"
imgui-glium-renderer = "0.3.0"
imgui-winit-support = {version = "0.3.0", features = ["winit-20"]}
glium = { version = "0.26", default-features = true }
```

and my code is basically just copied from the examples' Hello World (with the examples' `support` module too). (I can put that up in a repo if required.)

From (`cargo build`) I get 5 slightly different instances of `winit`-related errors, e.g.

```
error[E0308]: mismatched types
   --> src/support/mod.rs:125:55
    |
125 |                 platform.handle_event(imgui.io_mut(), gl_window.window(), &event);
    |                                                       ^^^^^^^^^^^^^^^^^^ expected struct `winit::window::Window`, found a different struct `winit::window::Window`
    |
    = note: expected reference `&winit::window::Window` (struct `winit::window::Window`)
               found reference `&winit::window::Window` (struct `winit::window::Window`)
    = note: perhaps two different versions of crate `winit` are being used?
```
and indeed, there are two versions of winit being compiled.
```
   Compiling winit v0.21.0
   Compiling winit v0.22.0
```

It looks like this stems from [Glium 0.26.0 pulling in Glutin 0.23](https://github.com/glium/glium/blob/af5683e603783c6af83837465105e9dc6ff61601/Cargo.toml#L36-L39) which [in turn pulls in winit 0.21](https://github.com/rust-windowing/glutin/commit/f071c722f725143d80638f1c5c12a76d9d8e1be8#diff-1b6d60f3f005be6e1e05f2803da7ccc6). 

The loose pinning https://github.com/Gekkio/imgui-rs/pull/300 in `imgui-winit-support` pulls in winit 0.22 in turn.

Glutin 0.24.0 (https://github.com/rust-windowing/glutin/commit/33aec609b6da89afc3c59b8b6e294b00c52fc12b) has a dependency on winit 0.22, so using Glutin 0.24.0 that would work...

I'm a relatively unseasoned rustacean, so:

* is there a mechanism with which I can force Glium's dependency on Glutin 0.23 to actually pull in Glutin 0.24, dependency pins be damned, or alternately,
* can I tell the loose pinning for `imgui-winit-support` to keep trucking with winit 0.21 for now?

As an aside, you can end up with a variant of this problem (same 0.21 + 0.22 thing) by removing `cargo.lock` in the examples directory and attempting to run an example.

**Comment by aloucks** [comment]
It's because of the range version specifier. This will cause cargo to pull in the latest version before `1.0`.

https://github.com/Gekkio/imgui-rs/blob/a3bafc7df147e972636f4f08393ea394abd55865/imgui-winit-support/Cargo.toml#L15

You can probably fix it with [patch](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#the-patch-section) or replace in your Cargo.toml.

**Comment by akx** [comment]
According to https://github.com/rust-lang/cargo/issues/5640#issuecomment-398374993 et al. `patch`ing transitive dependencies in a top-level Cargo.toml is not supported, boo. :(

**Comment by akx** [comment]
Ah, hey – Glium's `master` now has a commit that sets the Glutin dep to 0.24, so 

```
[dependencies]
imgui = "0.3.0"
imgui-glium-renderer = "0.3.0"
imgui-winit-support = {version = "0.3.0", features = ["winit-20"]}
glium = { git = "https://github.com/glium/glium", rev = "fb567dbc40718c8e5cdc9da41b7e4e803439376b" }

[patch.crates-io]
glium = { git = "https://github.com/glium/glium", rev = "fb567dbc40718c8e5cdc9da41b7e4e803439376b" }
```
works for me for the time being :)
