### ISSUE TITLE
winit 0.22 support

### ISSUE THREAD

**Issue by aentity** [Gekkio/imgui-rs#305]
Hello,

Is there coming winit 0.22 support soon in imgui-winit-support? Currently master is restricted to 0.21.

Thanks

**Comment by aclysma** [comment]
For me imgui-winit-support 0.3.0 is compatible with winit 0.22 and 0.3.1 is not. You might be able to get away with `imgui-winit-support = "=0.3.0"` for now. However, I can only say that it seems to work within winit 0.22 on macOS and possibly there is some sort of issue on other platforms, prompting restricting to winit <= 0.21.

This change is why 0.3.0 is working for me and 0.3.1 isn't
https://github.com/Gekkio/imgui-rs/commit/64022fbb2824391e79e0fdf5fbc6c1e32e583ff3

I totally understand the sentiment of "We can't promise forward compatibility with arbitrary versions" but given that imgui-winit-support uses a relatively small surface area of winit's API, it seems reasonable that some updates will remain compatible. So if it were me, I would leave  compatibility open-ended and only restrict when there is a known incompatibility. (Which, possibly there is such an incompatibility.. but I'm not aware of one.)

**Comment by aentity** [comment]
Thank you! Setting to =0.3.0 does fix this for me! I will close and let upgrade to 0.22 happen on own, thank you
