### ISSUE TITLE
lower framerate

### ISSUE THREAD

**Issue by jestarray** [Gekkio/imgui-rs#317]
is there a way to lower the frame rate? 60fps is a bit too excessive and I'd like to lower it down to 30 to conserve on battery life and resources.

**Comment by aloucks** [comment]
What do you mean? Imgui doesn't control the frame rate.

**Comment by jestarray** [comment]
Who controls the framerate?

**Comment by aloucks** [comment]
You do. 

ImGUI doesn't have anything to do with your window or rendering. The examples use a [small framework](https://github.com/Gekkio/imgui-rs/blob/master/imgui-examples/examples/support/mod.rs) based on winit that sets up the main loop that draws as fast as possible.

I think your question actually is related to when you should re-draw when using winit.

See also:

https://docs.rs/winit/0.22.1/winit/event_loop/enum.ControlFlow.html

https://docs.rs/winit/0.22.1/winit/window/struct.Window.html#method.request_redraw

https://docs.rs/winit/0.22.1/winit/event/enum.Event.html#variant.MainEventsCleared
