### ISSUE TITLE
support/mod.rs traits not satisfied in function calls

### ISSUE THREAD

**Issue by aaronhyperum** [Gekkio/imgui-rs#33]
Using your support/mod.rs brings up problems:

```
src/support/mod.rs:26:24: 26:38 error: the trait bound `glium::GlutinFacade: glium::backend::Facade` is not satisfied [E0277]
src/support/mod.rs:26         let renderer = Renderer::init(&mut imgui, &display).unwrap();
                                         ^~~~~~~~~~~~~~
src/support/mod.rs:26:24: 26:38 help: run `rustc --explain E0277` to see a detailed explanation
src/support/mod.rs:26:24: 26:38 note: required by `imgui::glium_renderer::Renderer::init`
src/support/mod.rs:87:23: 87:29 error: the trait bound `glium::Frame: glium::Surface` is not satisfied [E0277]
src/support/mod.rs:87         self.renderer.render(&mut target, ui).unwrap();
                                        ^~~~~~
src/support/mod.rs:87:23: 87:29 help: run `rustc --explain E0277` to see a detailed explanation
error: aborting due to 2 previous errors
```

[dependencies]
imgui = "0.0.9"
time = "0.1"
glium = "0.15.0"

Code from support/mod.rs torn from your latest release. Looking back at the 0.0.9 release, it doesn't seem to have changed.

**Comment by Gekkio** [comment]
This looks like a dependency version conflict. imgui-rs 0.0.9 uses glium 0.14.0, but you are declaring a dependency to 0.15.0 which is incompatible as per Rust library semver rules.
The compiler errors are a bit weird, but it's complaining about the incompatibility between 0.15 structs and 0.14 traits. [This comment](https://www.reddit.com/r/rust/comments/4sy81y/best_practice_for_exposing_library_dependencies/d5d81zv) explains a quite similar situation with another library.

**Comment by aaronhyperum** [comment]
I didn't notice that when I looked at the 0.0.9 source. As 0.0.10 seems to be using glium 0.15.0 I guess I'll close the thread. Thanks!
