### ISSUE TITLE
Combine DrawList from igGetBackgroundDrawList into WindowDrawList

### ISSUE THREAD

**Issue by lizhaoxian** [Gekkio/imgui-rs#334]
Current imgui-rs only exposes WindowDrawList, which does not have a easy way to access imgui's background drawlist

**Comment by lizhaoxian** [comment]
Hi there,

Can someone review the patch and let me know your opinion? It is useful to have background drawlist exposed at the same stage with WindowDrawList.

Better proposals are welcomed, I just came across this issue without deep knowledge about imgui / imgui-rs. ( Is it OK to PR onto master? )

**Comment by Gekkio** [comment]
Closing, since 0.5 allows accessing the background draw list
