### ISSUE TITLE
Relation of this project to a future "implot-rs"

### ISSUE THREAD

**Issue by 4bb4** [Gekkio/imgui-rs#337]
Hi there, thanks a lot for `imgui-rs`, I use it in a bunch of projects and it works really well!

Recently a plotting library has been created based on ImGUI (https://github.com/epezent/implot), and I'd like to take a go at creating Rust bindings for it. 

I've been wondering what the best approach would be to take in relation to the project here - I'd like to avoid replicating work that's in the repo here and also maybe follow a similar approach since it's clearly worked well. If anyone has opinions, let me know. I'd even be open to committing the work to the repo here if that is desired, but would also understand if you prefer to keep it in a separate repository.

**Comment by sonoro1234** [comment]
https://github.com/cimgui/cimplot is done as https://github.com/cimgui/cimgui (on which this repo is based).
So I think that all work done with cimgui would work on cimplot

**Comment by 4bb4** [comment]
That's true, and my plan was to use `cimplot` as well (thanks for creating that, by the way :D). I wondered if it would be better to for example add an `implot-sys` crate in the repo here, or build things in a separate repo altogether. My worry with the latter approach was that for such an `implot-sys` crate, I'd need to build and link ImGUI regardless, and with that I'd have to replicate a bunch of work from `imgui-sys`.

However, now that I've looked at https://github.com/Gekkio/imgui-rs/tree/master/imgui-sys a bit more and in particular https://github.com/Gekkio/imgui-rs/blob/master/imgui-sys/build.rs, it seems that part of the build is fairly little code and hence OK to duplicate though, so I think I'll start giving it a shot in a separate repo. We can still move it here if there's enough synergy or it's otherwise desired.

**Comment by sonoro1234** [comment]
In my project https://github.com/sonoro1234/LuaJIT-ImGui cimgui is included side by side with cimplot and the modification for adding cimplot was minimal

**Comment by aloucks** [comment]
Assuming [this PR](https://github.com/Gekkio/imgui-rs/pull/339) is merged, you'll be able to just make `imgui-sys` a dependency of a sys crate containing `implot` and add the header include path in your `build.rs` script.

**Comment by 4bb4** [comment]
@aloucks nice, thanks! I'll try doing it this way.

**Comment by 4bb4** [comment]
I think this can be closed - I managed to just depend on the `imgui-sys` crate over at https://github.com/4bb4/implot-rs and get things working that way with the help of @aloucks. Thanks for all the input!

**Comment by 4bb4** [comment]
@Gekkio would it be possible to create a bugfix release in the near future that includes https://github.com/Gekkio/imgui-rs/pull/339? As things stand, I think I can't publish `implot-rs` on crates.io because I depend on `master` here (correct me if I'm wrong, I think dependencies need a version specified for crates.io to accept the project).
