### ISSUE TITLE
Drag and Drop support

### ISSUE THREAD

**Issue by RoyJacobs** [Gekkio/imgui-rs#348]
I have written a very simple wrapper around imgui's drag and drop support, but I noticed that the flags related to this (`ImGuiDragDropFlags`) are located in `legacy.rs`. Does this mean they should not be used?

Otherwise I'd be happy to create a small pull request to add drag and drop support.

Basic usage for the source:
```
DragDropSource::new().build(&ctx.ui, || {
    // This is a global method since it is setting the global clipboard data. Should probably namespace this.
    set_drag_drop_payload(im_str!("SOME_ID"), &my_data, Condition::Once);
});
```

And for the target (currently panics if the type of payload doesn't match what's in the clipboard, should probably use a `Result` instead):
```
DragDropTarget::new().build(ctx.ui, |d| {
    d.accept_payload(im_str!("SOME_ID"), |payload: &TypeOfPayloadData| {
        my_var = Some(payload.clone());
    });
});
```

**Comment by Gekkio** [comment]
They're in legacy because they use pre-0.1 naming and the old mechanism of declaration (no references to imgui-sys constants).
So, they should not be used as is, but replaced with rewritten flags struct based on the 0.1+ way.

The last time I investigated drag&drop support, there was something non-trivial about writing a safe API for it, so I gave up. But it's been a while and I can't remember what the problem was.

**Comment by RoyJacobs** [comment]
I'm also not sure how to approach it for structs that aren't simply a collection of plain old data (e.g. some `string`s, `f32`s, etc). Ideally there would be some way to restrict the type of data inside the structs that can be used as a drag/drop payload, but I'm not sure how to enforce that. I'll leave it for now.

**Comment by Boscop** [comment]
Any update on this? It would be very useful to have drag & drop support :)

**Comment by sanbox-irl** [comment]
Hiya -- I made a pr https://github.com/imgui-rs/imgui-rs/pull/428 for dragdrop support. it hasn't been accepted, but if anyone here would like to take a look at it, more eyes would be welcome
