### ISSUE TITLE
DragFloat for f64

### ISSUE THREAD

**Issue by cosmicchipsocket** [Gekkio/imgui-rs#363]
This would be nice to have, since some of my data formats rely on using f64 and currently I have to convert to f32 and back to put the values in a DragFloat, meaning that there's loss of precision.

**Comment by Gekkio** [comment]
This will be supported in 0.5, because the drag widget API has been redesigned to use the generic scalar data type mechanism (supports i8, u8, i16, u16, i32, u32, i64, u64, f32, f64)

```rust
let mut my_double: f64 = 0.0;
Drag::new(im_str!("Double the precision, double the fun"))
  .range(0.0 ..= 1.0)
  .build(&ui, &mut my_double);
```

**Comment by Gekkio** [comment]
Closing, since 0.5 has been released :tada:
