### ISSUE TITLE
What's the recommended way of applying a custom style?

### ISSUE THREAD

**Issue by noomly** [Gekkio/imgui-rs#364]
I've been introducing myself to imgui with imgui-rs and as the title indicates, I'm currently trying to apply a custom style.

Reading through https://github.com/ocornut/imgui/issues/707, I understood that for this purpose it seems to be a good practice to edit directly `Style::colors`. Although it doesn't seem possible to index it with `StyleColor`. Right now my solution looks like this:

```rust
pub fn set_super_dark_style(style: &mut Style) {
    let colors = &mut style.colors;

    let mut sc = HashMap::new();
    for (i, style_color) in StyleColor::VARIANTS.iter().enumerate() {
        sc.insert(style_color, i);
    }

    style.frame_border_size = 1.0;
    style.frame_padding = [4.0, 2.0];
    style.item_spacing = [8.0, 2.0];
    // ...

    colors[*sc.get(&StyleColor::Text).unwrap()] = [1.00, 1.00, 1.00, 0.95];
    colors[*sc.get(&StyleColor::TextDisabled).unwrap()] = [0.50, 0.50, 0.50, 1.00];
    colors[*sc.get(&StyleColor::WindowBg).unwrap()] = [0.13, 0.12, 0.12, 1.00];
    // ...
}
```

I roughly converted it from https://github.com/ocornut/imgui/issues/707#issuecomment-431702777. It doesn't look ideal though and it seems some colors are confused. As I didn't find documentation on the matter, I'm wondering if there is a better way of handling this?

**Comment by Gekkio** [comment]
Indexing with `StyleColor` is possible, but you need to do it with `style` and not `style.colors`:

```
style[StyleColor::Text] = [1.00, 1.00, 1.00, 0.95];
style[StyleColor::TextDisabled] = [0.50, 0.50, 0.50, 1.00];
style[StyleColor::WindowBg] = [0.13, 0.12, 0.12, 1.00];
```

**Comment by noomly** [comment]
Sorry for the late reply. Your answer solved my problem entirely, thank you.
