### ISSUE TITLE
Expose GroupToken

### ISSUE THREAD

**Issue by vinterskog** [Gekkio/imgui-rs#367]
Hi there,
I'd like to construct a group and I can't use a closure, so I need to use begin_group(). However, I can't store the token because GroupToken is in imgui::layout which is private. Maybe I'm missing something, but GroupToken should be accessible, otherwise begin_group() is unusable right now if the token has to be stored non-locally.

**Comment by Gekkio** [comment]
It's an oversight that I fixed just now in e5c6eb97f376084c87099bf8d52c9f7bcef3bfb4. The fix will be included in 0.5 :smile:
