### ISSUE TITLE
Publish imgui-winit-support 0.6.0

### ISSUE THREAD

**Issue by maxded** [Gekkio/imgui-rs#387]
Now that #385 has been merged, could we get a release of `imgui-winit-support` 0.6.0? Or would you like to release everything imgui-rs related together in #368? Not sure what standard procedure is here. :)

**Comment by Gekkio** [comment]
Yeah, I'll publish a release this weekend :smile: 
Everything is released in lock-step so in practice all core imgui-rs crates will be bumped to 0.6.0 and released.

**Comment by Gekkio** [comment]
0.6 is here :tada:
