### ISSUE TITLE
No Push/PopStyleVar()?

### ISSUE THREAD

**Issue by ApoorvaJ** [Gekkio/imgui-rs#39]
Is there a way to push/pop styles, or are we restricted to style_mut? If there's no push/pop, is this limitation of a closure-based API vs a begin()/end() one?

**Comment by Gekkio** [comment]
It's just something that hasn't been implemented yet. Based on a quick look those functions are probably memory-safe, but abort the process if you do something incorrect (e.g. push once, pop twice). I'd prefer a nicer API, but it's probably a reasonable compromise to just wrap those and trust that the library users do the right things.

**Comment by ApoorvaJ** [comment]
Thanks for the reply. Regrettably, I'm not at a level of proficiency with Rust yet where I can write up an API and send a pull request. Feel free to close this bug or keep it open, as you see fit.

**Comment by bjadamson** [comment]
This functionality got merged! I think we can close this :)
