### ISSUE TITLE
Support for repetition

### ISSUE THREAD

**Issue by mruegenberg** [Gekkio/imgui-rs#40]
In the original ImGui, there is `ImGui::PushID(i);`/`ImGui::PopID()`. This allows adding e.g the same UI code for each item of a collection without name clashes.

Probably, it would be more elegant to have some kind of wrapper for collections (though there might be other cases where PushID/PopID is desirable) instead of directly implementing PushID/PopID. Also note that this is more general than just using tree nodes.

If there is already some way of adding UI for each item of a collection, it would be good to add this to an example.

**Comment by Gekkio** [comment]
Basic support for ID stack manipulation with integer numbers was released in v0.0.13.

Now you can do:

```rust
ui.with_id(12345, || {
  // do stuff
});
```

or if you want to push and pop manually (make sure you don't pop an empty stack!):

```rust
ui.push_id(12345);
// do stuff
ui.pop_id();
```

Please reopen this issue or open a new one if this API doesn't yet fulfill your requirements :smiley:
