### ISSUE TITLE
test_window.rs using glium

### ISSUE THREAD

**Issue by ocornut** [Gekkio/imgui-rs#5]
Perhaps test_window.rs shouldn't be relying on glium, may be misleading?

**Comment by Gekkio** [comment]
Well, it has to use something for rendering, and glium renderer is already a part of the library. Note that test_window.rs is just a separate example binary, so it is not part of the library. The library has a call to show a test window, but that uses the C++ version. The only reason test_window.rs exists is to reimplement all features from the C++ version so people can compare them side by side or use it as a reference.

**Comment by ocornut** [comment]
Fair, I didn't realise it was a standalone application by itself and not just the imgui user code.
