### ISSUE TITLE
ImString as String

### ISSUE THREAD

**Issue by viperscape** [Gekkio/imgui-rs#51]
Is there a way to retrieve the underlying string of ImString?

https://github.com/Gekkio/imgui-rs/blob/master/src/string.rs#L10
It'd probably look something like this:

```rust
impl From<ImString> for String {
    fn from(value: ImString) -> String { 
        let mut s = value.0;
        let _ = s.pop();
        s
    }
}
```

Except also a Referenced version of ImString would be useful, even if it clones the underlying string. 
Reasoning is that I want an ui input field to drive some functionality that takes in Strings.

**Comment by Gekkio** [comment]
You can call `to_str()` to get a `&str` and then call any normal `&str` functions such as `to_owned()`:

```rust
fn do_stuff(value: &ImString) {
  let s = value.to_str().to_owned(); // s is a String
}
```

`&ImString` also has a Deref to `&str` so you don't actually even need to call `to_str()` in most cases:

```rust
fn do_stuff_with_str(value: &str) { }

fn do_stuff() {
  let ims: ImString = ...
  do_stuff_with_str(&ims);
}
```

It also means that you can all any normal `&str` functions:

```rust
fn do_stuff(ims: &ImString) {
  // &str has a function called starts_with
  if ims.starts_with("banana") {
  }
  // &str has a function called lines
  for line in ims.lines() {
  }
  // and finally...&str has a function called to_string()
  let s = ims.to_string();
}
```

**So, the shortest way to do it is just to call** `to_string()` :smiley: 

I intend to write documentation at some point about the new way of handling imgui strings, but the basic idea is that `&ImString` and `&ImStr` both can work exactly like `&str` (but `&mut ImString` is not `&mut str`!).

**Comment by viperscape** [comment]
Ah you rock, thank you! :-)
