### ISSUE TITLE
imgui-gfx-renderer: colors are too bright

### ISSUE THREAD

**Issue by Gekkio** [Gekkio/imgui-rs#54]
This is probably an SRGB vs RGB issue, but I haven't figured out yet how to avoid it.

**Comment by Feilkin** [comment]
The problem is caused by glutin, which uses sRGB over RGB, even when told not to. I have managed to work around this problem by using sRGB for my main target, and generating separate RGB target which I use for imgui.

**Comment by Gekkio** [comment]
This is no longer a big problem since the support code does manual gamma adjustment.
