### ISSUE TITLE
imgui-gfx-renderer: Support for backends other than OpenGL

### ISSUE THREAD

**Issue by Gekkio** [Gekkio/imgui-rs#55]
imgui-gfx-renderer includes shaders only for OpenGL, so other backends don't work right now.

**Comment by tangmi** [comment]
I took an attempt at this: https://github.com/tangmi/imgui-rs/commit/616d61767f207bcc313c79fff480e2bd15a9e065. I got as far as writing and compiling HLSL shaders and including the bytecode with the `imgui-gfx-renderer` lib.

The main thing preventing this from working is that HLSL only supports constant buffers (and does not support bare global values (GLSL uniforms)). To get this working I can think of two options:
- Define a second pipeline declaration for HLSL that includes a constant buffer, although I'm not entirely sure what's the nicest way to have the renderer branch on the pipeline (which is part of `Renderer`'s type) given the requested `shaders` value.
- Only support OpenGL >= 3.1 and >= ES 3.0 and switch all the shaders to use constant buffers/interface blocks.

Thanks for working on this project! Cheers!
