### ISSUE TITLE
Finish TextFilter

### ISSUE THREAD

**Issue by tetenpapier** [Gekkio/imgui-rs#649]
I would like to use the TextFilter on a list but I don't find anything about it in the documentation.

The binding is already written (#313 & [in code](https://github.com/imgui-rs/imgui-rs/blob/f523dd2501daa683f311359cae8eed5444e0b594/imgui-sys/src/bindings.rs#L1202)), but not the API.

**Comment by dbr** [comment]
Are you referring to this https://github.com/ocornut/imgui/blob/v1.86/imgui_demo.cpp#L1357-L1376 ?

If so I think they are available in API:

1. The flags like `ImGuiInputTextFlags_CharsUppercase` are available as `InputText::chars_uppercase` https://docs.rs/imgui/0.8.0/imgui/struct.InputText.html#method.chars_uppercase etc
2. From #516, the callback based filters are usable via https://docs.rs/imgui/0.8.0/imgui/struct.InputText.html#method.callback and the trait mentioned there. I suspect it might be quite tricky to implement purely based on the docs, so there is an example which is probably clearer here: https://github.com/imgui-rs/imgui-rs/blob/v0.8.2/imgui-examples/examples/text_callbacks.rs

**Comment by teteenpapier** [comment]
No, I'm referring to https://github.com/ocornut/imgui/blob/v1.86/imgui_demo.cpp#L5642-L5660.

I've searched `Filter` in the Rust documentation but only found the filters for `InputText`. I can make my own filter but I prefer to use the native features of ImGUI.

**Comment by dbr** [comment]
Ahh, I see! That is indeed not yet exposed in the API yet. I don't have time to look into this currently, but a PR would be welcomed - it should be relatively simple to make the bindings (although anything dealing with strings can be a bit tricky because of the Rust String vs C++'s null-terminated strings)

**Comment by dbr** [comment]
Closing - was done in #658 and will be released with v0.9 :partying_face:
