### ISSUE TITLE
Missing binding to GetWindowSize

### ISSUE THREAD

**Issue by SED4906** [Gekkio/imgui-rs#651]
**Is your feature request related to a problem? Please describe.**
There is currently no binding to the GetWindowSize function in imgui.

**Describe the solution you'd like**
Add a binding for the GetWindowSize function.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by dbr** [comment]
I think this is exposed via [`ui.window_size()`](https://docs.rs/imgui/0.8.0/imgui/struct.Ui.html#method.window_size) ?

https://github.com/imgui-rs/imgui-rs/blob/v0.8.2/imgui/src/window/mod.rs#L152-L157

**Comment by SED4906** [comment]
oh, I didn't notice that. thank you!
