### ISSUE TITLE
Using Image on main window still renders inside a "Debug" window

### ISSUE THREAD

**Issue by dcvz** [Gekkio/imgui-rs#730]
**Describe the bug**
I'm trying to use a custom texture but instead of using it in a sub window - I want to draw it on the main window where I'm already drawing a menu bar. However, for some reason things get drawn into a "Debug" window.

**To Reproduce**

Take example for custom textures and change the main() to have this:

```
fn main() {
    let mut my_app = CustomTexturesApp::default();

    let mut system = support::init(file!());
    my_app
        .register_textures(system.display.get_context(), system.renderer.textures())
        .expect("Failed to register textures");
    system.main_loop(move |_, ui| 
        Image::new(my_app.my_texture_id.unwrap(), [100.0, 100.0]).build(ui)
    );
}
```

**Expected behavior**
The image should be drawn in the main window since no sub window was specified

**Screenshots**
<img width="1055" alt="Screenshot 2023-06-13 at 11 37 18" src="https://github.com/imgui-rs/imgui-rs/assets/2475932/a7da236f-3556-4146-8944-713ff3902e06">

**Please describe your environment**
 - imgui-rs 0.11.0
 - macOS

**Comment by aunyks** [comment]
@dcvz Do you have any links or code snippets to help understand this with the Rust library? I'm also running into this but am having trouble translating the CPP examples to use this crate.
