### ISSUE TITLE
`tree_node`'s with the same name seem to be linked?

### ISSUE THREAD

**Issue by Ploppz** [Gekkio/imgui-rs#76]
Probably not something that this library is responsible for but.. maybe you know a way to get around this:
Using `ui.tree_node` recursively, siblings with the same name all open when I click one of them, and they have the same value.
![ss](http://i.imgur.com/WwJrjI3.png)
Is this expected?

**Comment by Gekkio** [comment]
Yeah this is probably a consequence of imgui's default "label is ID" mechanism used in some places. What does your code look like? Are you just calling `ui.tree_node(somelabel).build()`? If yes, you can probably fix this by calling `ui.tree_node(some_id_string).label(somelabel).build()` instead to separate the IDs from the labels. Unfortunately non-ImStr IDs are not yet supported so you can't use something like a numeric index directly.

**Comment by Ploppz** [comment]
Thanks! That worked.
