### ISSUE TITLE
Show style windows - is this possible?

### ISSUE THREAD

**Issue by Ploppz** [Gekkio/imgui-rs#77]
I'm using [this](https://github.com/Gekkio/imgui-rs/blob/master/imgui-examples/examples/support_gfx/mod.rs) for `gfx` support. In the `run_ui` closure, I try to show the style editor:
```
ui.show_style_editor(ui.imgui().style_mut());
```

It doesn't work when ui isn't `&mut`. But even if it were, `imgui()` doesn't take `&mut self` it seems.

**Comment by Gekkio** [comment]
This doesn't seem to be possible at the moment due to Rust borrowing rules. Maybe I should make `ImGuiStyle` derive `Copy` so you could store the "temporary" style separately and copy before the UI rendering on each frame.

**Comment by Gekkio** [comment]
Heh, I completely forgot that editing the current style directly is actually supported but with a different function :smile: 

Try
```
ui.show_default_style_editor();
```
