### ISSUE TITLE
Weird child_frame cpu usage

### ISSUE THREAD

**Issue by ghost** [Gekkio/imgui-rs#80]
For some reason using ui.child_frame causes 95-100% cpu usage.
Replicated here: https://github.com/nick70/imgui-rs-child_frame-cpu-issue
I don't know if its imgui-rs or some other crate or me being dumb.

Ubuntu MATE 16.04.3

EDIT: cpu usage is around 8% on Manjaro 17.0.4

**Comment by Gekkio** [comment]
I don't see any obvious problems in the code but can reproduce this issue on my machine. In some quick profiling a huge amount of time was spent in syscalls, but I should probably investigate further to verify this.

**Comment by Gekkio** [comment]
I'm pretty sure this was fixed in cddef5ee3463c090a5316ab9583b9ce526dfd04a

Please reopen and/or open a new issue if you still see problems! :smiley:
