### ISSUE TITLE
Restore ImFontConfig contructor

### ISSUE THREAD

**Issue by o01eg** [Gekkio/imgui-rs#88]
`cimgui` 1.52.1 restored accidentally removed in previous versions default constructor for ImFontConfig: https://github.com/Extrawurst/cimgui/pull/43

**Comment by o01eg** [comment]
Is it going to be restored or there another way to create `ImFontConfig`?

**Comment by malikolivier** [comment]
@Gekkio I think this issue can be closed. `ImFontConfig_DefaultConstructor` was added back in #119 .
