### ISSUE TITLE
Should `&mut self` be used for all state modifying functions?

### ISSUE THREAD

**Issue by anderejd** [Gekkio/imgui-rs#90]
Hi!

I've been playing around with this wrapper for a couple of hours now and I am very impressed so far :) And imgui seems amazing. Thank you so much for this crate!

This is more of a question than a bug report: There are multiple functions that seems like they mutates state that takes a `&self`. I did expect `&mut self`. What is the reasoning behind this?

**Comment by Gekkio** [comment]
Thanks! :smiley: 

I've thought about the same thing multiple times myself, but my current understanding is that imgui-rs basically uses a form of interior mutability that makes it OK to use `&self`. The basic idea is that neither `ImGui` and `Ui` actually contain any of the real state that is modified, but they simply track *when* things are allowed to happen. It's also impossible to take a reference to some internal state that could be modified by any of the functions using `&self`. So when you call a mutating function that takes `&self`, we know that there are no mutable references to internal state. If the underlying imgui library was written in Rust, `RefCell` would probably be used to achieve interior mutability like this, but in this case it's more of an implicit thing.

It's of course possible there are holes in the system, but those are actual bugs that are fixed when found. For example, if you found a way to take a normal reference to some state and modify it with a function taking `&self`, that would be a bug.

**Comment by anderejd** [comment]
Ok thanks for the explanation.
I have a feeling though (have not read the docs yet) that using it from multiple threads or from anything but the main thread is a bad idea, so I'm going to keep all imgui interaction on the main thread.

**Comment by anderejd** [comment]
Ok thanks for the explanation.
I have a feeling though (have not read the docs yet) that using it from multiple threads or from anything but the main thread is a bad idea, so I'm going to keep all imgui interaction on the main thread.

**Comment by Gekkio** [comment]
Yeah, it's unfortunately not explicitly mentioned in the docs at the moment, but imgui-rs is not thread-safe. The underlying dear imgui library is not thread-safe and uses global mutable state, so the wrapper is limited by this design decision.

**Comment by anderejd** [comment]
Good to know. Maybe copy paste that last info to the readme? :)

**Comment by kgv** [comment]
> imgui-rs is not thread-safe

But it have auto impl Send and Sync. Maybe it have to:

```rust
impl !Send for ImGui {}
impl !Sync for ImGui {}
```
?

**Comment by anderejd** [comment]
@kgv The need for that would go away if switching over to `&mut self` since that is not Send nor Sync. I have not kept myself up to date with this library for a while, maybe it's already fixed?

**Comment by kgv** [comment]
@anderejd I'm not sure about `&mut self`, @Gekkio described that imgui-rs uses interior mutability. But if it uses interior mutability and is not thread-safe => we have to implement !Send and !Sync.

This is from documentation:
> A data race has Undefined Behavior, and is therefore impossible to perform in Safe Rust. Data races are mostly prevented through rust's ownership system: it's impossible to alias a mutable reference, so it's impossible to perform a data race. Interior mutability makes this more complicated, which is largely why we have the Send and Sync traits (see below).

**Comment by Gekkio** [comment]
It's true, `!Send` and `!Sync` should be implemented. This will be fixed in 0.1.
BTW, once upstream Dear ImGui switches to explicit contexts (vs current approach of global mutable "current context"), `Send` becomes OK so you can send ImGui contexts to other threads (but not share them)

**Comment by Gekkio** [comment]
`!Send` and `!Sync` are now correctly handled in `0.1.0-rc.1`
