### ISSUE TITLE
Examples don't work on OSX

### ISSUE THREAD

**Issue by jherman3** [Gekkio/imgui-rs#98]
I'm trying to integrate this into a Glium project and am running into issues on OSX. I thought the issue could be with the way I'm integrating it so I tried running the examples and am having issues.
The hello_world example just gives a blank white screen.
The test_window example renders a clickable menu but the mouse cursor doesnt line up with where Imgui thinks the cursor is (you have to click about half a window above where the item is).
It also looks like the alignment is off and part of the menu gets chopped off.
<img width="1136" alt="screen shot 2018-01-12 at 3 31 01 pm" src="https://user-images.githubusercontent.com/7232353/34894164-400905fe-f7ae-11e7-8398-e63742b366f6.png">

I'm on OSX 10.13.2 with rust nightly.

**Comment by Gekkio** [comment]
Sounds like this might be the same DPI scaling issue as https://github.com/Gekkio/imgui-rs/issues/71. Unfortunately there's no good solution yet :cry:

**Comment by jherman3** [comment]
Update on this issue: Applying https://github.com/tomaka/winit/pull/359 seems to fix all the Glium examples. It seems discussion has stopped on that PR though.
Here's the test_window example working:
<img width="1136" alt="screen shot 2018-02-16 at 2 51 28 pm" src="https://user-images.githubusercontent.com/7232353/36326410-f29bcdf6-1328-11e8-827b-684b17982171.png">

**Comment by parasyte** [comment]
This should be fixed in `winit` 0.12.0: https://github.com/tomaka/winit/blob/master/CHANGELOG.md#version-0120-2018-04-06

**Comment by parasyte** [comment]
There's now an open PR for updating glium to use winit 0.12: https://github.com/glium/glium/pull/1685
And my PR for gfx has been merged: https://github.com/gfx-rs/gfx/pull/1927 (Still awaiting a release.)
